runtime: nodejs20

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15
  min_idle_instances: automatic

entrypoint: npm build && npm start

env_variables:
  NODE_ENV: "production"

handlers:
- url: .next/static/(.*\.(json|js))
  static_files: .next/static/\1
  upload: /.next/static/(.*)
- url: /static/(.*)
  static_files: .next/static/\1
  upload: .next/static/(.*)
- url: /.*
  static_files: .next/\1
  upload: .next/(.*)
